name: 'Deploy container to latest tag'

on:
  push:
    branches:
      - main

jobs:
  build-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_KEY }}
        uses: docker/login-action@v1
      - name: Build the Docker image
        run: |
          echo "Building container..."
          docker build -f Dockerfile -t ahrenstein/bankless-bot:latest .
          echo "Pushing container to Docker Hub..."
          docker push ahrenstein/bankless-bot:latest
          echo "Done!"
